# -*- coding: utf-8 -*-
"""Telecom_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mccid9tGKJ9qT38upqehzqGTVYQTiwVY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/churn-bigml-80.csv")
df.head(10)

"""**Data Cleaning**: Ensure Total day/eve/night minutes and charges are numerically consistent so the model doesn't fail on "Object" types.

**Outlier identification**: Find "extreme users" (e.g., unusually high Customer service calls) who are statistically almost certain to churn.

**Univariate Plotting:** Understand the Class Imbalance (how many churners vs. non-churners) to see if the data is skewed.

**Bivariate Plotting:** Directly compare features against Churn (e.g., International Plan vs. Churn) to see which service has the highest failure rate.

**EDA Analysis:** Determine if usage volume (minutes) or service quality (calls to helpdesk) is the bigger driver of customer loss.
"""

df.isnull().sum()

df.info()

#Converting the target variable as int
df['Churn'] = df['Churn'].astype(int)

# 2. OUTLIER IDENTIFICATION
# Customer service calls are a common area for outliers
plt.figure(figsize=(6, 4))
sns.boxplot(x=df['Customer service calls'])
plt.title('Outlier Detection: Customer Service Calls')
plt.show()

"""Focused on Customer service calls for outlier detection because it is the dataset's strongest behavioral signal for dissatisfaction. While usage metrics (like minutes) vary naturally, extreme values in service calls are direct indicators of a failing customer relationship"""

sns.boxplot(x=df['Total day minutes'])
plt.title('Outlier Detection: Total Day Minutes')
plt.show()

sns.boxplot(x=df['Total day charge'])
plt.title('Outlier Detection: Total Day Charge')
plt.show()

sns.boxplot(x=df['Total eve minutes'])
plt.title('Outlier Detection: Total Evening Minutes')
plt.show()

# 3. UNIVARIATE PLOT
# Visualizing the distribution of the Churn (Target) variable
plt.figure(figsize=(6, 4))
sns.countplot(x='Churn', data=df, palette='viridis')
plt.title('Univariate: Churn Distribution (0=Stayed, 1=Left)')
plt.show()

"""*   It shows the ratio of the customers who stayed and those who left

*   Roughly 85% stayed and only 15% left


*   If we use dumb model(makes the simplest model prediction without looking at any data features) the accuracy would be 85% but 0% useless
*   Use precision or recall to see if you are actually catching the churners


"""

#Count Plot: Comparing the frequency of Churn for each number of calls
plt.figure(figsize=(10, 5))
sns.countplot(x='Customer service calls', hue='Churn', data=df, palette='viridis')
plt.title('Bivariate: Churn Rate by Number of Service Calls')
plt.xlabel('Number of Customer Service Calls')
plt.ylabel('Count of Customers')
plt.legend(title='Churn', labels=['Stayed (0)', 'Left (1)'])
plt.show()

"""### **Key Insight**


1.   Customer making 0 to 3 phone calls are highly likely to stay
2.   Customers making 5,6 or 9 calls are the outliers


"""

# Plot 1: Total day minutes vs Churn
plt.subplot(1, 2, 1)
sns.boxplot(x='Churn', y='Total day minutes', data=df, palette='Set2')
plt.title('Bivariate: Day Minutes vs Churn')
plt.tight_layout()
plt.show()

"""This plot reveal that the median for Churn = 1 is higher than Churn =0.This suggest that users who pay more are actually more likely to leave,possibly seeking better unlimited plans elsewhere."""

# Plot 2: Total day charge vs Churn
plt.subplot(1, 2, 2)
sns.boxplot(x='Churn', y='Total day charge', data=df, palette='Set2')
plt.title('Bivariate: Day Charge vs Churn')
plt.tight_layout()
plt.show()

"""1.These two plots will look almost exactly the same because Total day charge is a direct linear calculation of Total day minutes.

2.Since they provide the same info one of these features should be removed to avoid redundancy
"""

# 5. EDA CORRELATION ANALYSIS
# Understanding which numerical features move together
plt.figure(figsize=(10, 8))
numeric_df = df.select_dtypes(include=[np.number])
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('EDA: Feature Correlation Heatmap')
plt.show()